Repository fusionjs/eslint-config-fusion, pull requests merged in 2019-04, with the labels that each got.

#136 Add react hook rules and peerDep
  docs/migrations/00136.md
  index.js
  package.json
  yarn.lock
Labels: breaking, bugfix

#137 Release v5.0.0-0
  package.json
Labels: release

#138 Release v5.0.0
  package.json
Labels: release

#139 Fix missing react version warning
  index.js
Labels: bugfix

#140 Fix version warning when react isn't installed
  index.js
Labels: bugfix
